- namespace: experiments.awesomeBar
  description: Listen to awesome bar interactions

  types:
  - id: awesomeBarState
    $schema: "http://json-schema.org/draft-04/schema"
    type: object
    properties:
      rankSelected:
        type: number
      numCharsTyped:
        type: number
      numSuggestionsDisplayed:
        type: number
      suggestions:
        type: array
        items:
          type: string
    required: ["numSuggestionsDisplayed", "rankSelected", "bookmarkAndHistoryUrlSuggestions", "bookmarkAndHistoryRankSelected", "numCharsTyped", "selectedStyle"]
    testcase: {bookmarkAndHistoryRankSelected: -1, bookmarkAndHistoryUrlSuggestions: [], numCharsTyped: 3, numSuggestionsDisplayed: 11, rankSelected: 2, selectedStyle: "action searchengine suggestion"}

  functions:
  - name: start
    type: function
    async: true
    description: Start listening to awesome bar interactions
    parameters: []
  - name: stop
    type: function
    async: true
    description: Stop listening to awesome bar interactions
    parameters: []

  events:
  - name: onAutocompleteSuggestionSelected
    type: function
    description: Fires when a suggestion has been suggested in the awesome bar autocomplete popup.
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onFocus
    type: function
    description: Enter the awesome bar
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onBlur
    type: function
    description: Exit the awesome bar
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onInput
    type: function
    description: Character typed/deleted
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onAutocompleteSuggestionsDisplayed
    type: function
    description: Autocomplete popup show
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onAutocompleteSuggestionsHidden
    type: function
    description: Autocomplete popup hide
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
  - name: onAutocompleteSuggestionsUpdated
    type: function
    description: Autocomplete suggestions changed
    parameters:  # for the callback
    - name: awesomeBarState
      $ref: awesomeBarState
